name: college360
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_image: ^0.0.6+1
  firebase_storage: ^10.2.16
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.11
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  dropdown_button2: ^1.2.5
  flutter_secure_storage: ^5.0.2
  provider: ^6.0.2
  timeago: ^3.2.2
  animated_flip_counter: ^0.2.4
  image_picker: ^0.8.5+3
  page_view_dot_indicator: ^1.1.0
  file_picker: ^4.6.0
  dio: ^4.0.6
  path_provider: ^2.0.10
  open_file: ^3.2.1
  firestore_search: ^0.1.9
  share_plus: ^4.0.7
  percent_indicator: ^4.0.1
  lottie: ^1.3.0
  introduction_screen: ^3.0.2
  cached_network_image: ^3.2.0
  gallery_saver: ^2.3.2
  image_gallery_saver: ^1.7.1
  flutter_firebase_chat_core: ^1.6.2
dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/Icons/
  fonts:
     - family: PlayfairDisplay
       fonts:
         - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
         - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
           style: italic
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Regular.ttf
     - family: OpenSans
       fonts:
          - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
          - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
     - family: AlexBrush
       fonts:
          - asset: assets/fonts/AlexBrush-Regular.ttf


